name: Build Documentation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          python-version: 3.7
          activate-environment: rmg_env
      - name: Install sphinx
        run: conda install -y sphinx
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Install and compile RMG
        run: |
          cd ..
          git clone https://github.com/ReactionMechanismGenerator/RMG-database.git
          cd RMG-Py
          sed -i '/embedsignature/s/# //g' setup.py
          make
      - name: Make documentation
        env:
            GH_TOKEN: ${{ secrets.RMG_DEV_TOKEN }}
        run: |
          make -C documentation continous_integration_setup clean html
      - name: Check documentation links
        continue-on-error: true
        run: |
          cd documentation
          sphinx-build -b linkcheck -d build/doctrees/ source/ build/linkcheck | grep -e broken -e redirect
      - name: Test documentation
        if: ${{  github.event_name == 'pull_request' }}
        run: |
          cd documentation
          sphinx-build -b html -d build/doctrees/ source/ build/html -w errors.log -W --keep-going
      - name: Publish documentation
        if: ${{  github.event_name == 'push' && github.repository == 'ReactionMechanismGenerator/RMG-Py' }}
        env:
            COMMITMESSAGE: "Automatic documentation rebuild"
            GIT_AUTHOR_NAME: "RMG Bot"
            GIT_AUTHOR_EMAIL: "rmg_dev@mit.edu"
            GIT_COMMITTER_NAME: "RMG Bot"
            GIT_COMMITTER_EMAIL: "rmg_dev@mit.edu"
        run: |
          make -C documentation publish
